// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-XcntNpF1KcVVy_NQR94CdR7KvqQgNv4',
    appId: '1:119732894769:web:f55a87d5a93c8f8273e910',
    messagingSenderId: '119732894769',
    projectId: 'expense-tracker-app-c4910',
    authDomain: 'expense-tracker-app-c4910.firebaseapp.com',
    storageBucket: 'expense-tracker-app-c4910.firebasestorage.app',
    measurementId: 'G-X2PX1F6WYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwGlx1UPJuXIAO0mugEdpcWEVVkDl5CCU',
    appId: '1:119732894769:android:4c0cd06a3fe54e0973e910',
    messagingSenderId: '119732894769',
    projectId: 'expense-tracker-app-c4910',
    storageBucket: 'expense-tracker-app-c4910.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHofLsCbpaT_0Hw3NwgUJqInNPpzSgjac',
    appId: '1:119732894769:ios:994308ed27e8727473e910',
    messagingSenderId: '119732894769',
    projectId: 'expense-tracker-app-c4910',
    storageBucket: 'expense-tracker-app-c4910.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHofLsCbpaT_0Hw3NwgUJqInNPpzSgjac',
    appId: '1:119732894769:ios:994308ed27e8727473e910',
    messagingSenderId: '119732894769',
    projectId: 'expense-tracker-app-c4910',
    storageBucket: 'expense-tracker-app-c4910.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-XcntNpF1KcVVy_NQR94CdR7KvqQgNv4',
    appId: '1:119732894769:web:97a4b65cfe6051e473e910',
    messagingSenderId: '119732894769',
    projectId: 'expense-tracker-app-c4910',
    authDomain: 'expense-tracker-app-c4910.firebaseapp.com',
    storageBucket: 'expense-tracker-app-c4910.firebasestorage.app',
    measurementId: 'G-C6HHXHJFBF',
  );
}
